---
 
- hosts: all
  become: true
  tasks:

  - name: install apache and php
    package:
      name:
        - "{{ apache package }}"
        - "{{ php package }}"
      state: latest
      update_cache: yes
