---

- hosts: srv1@192.168.1.41
  become: true
  tasks:

  - name: update repository index
    apt:
      update-cache: yes    
    #when: ansible_distribution == "Ubuntu"
    #The following is more robust  
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
